name: Cerys
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  nyxx: ^1.0.0
  nyxx_commander: ^1.0.0
  dotenv: ^2.0.0
  toml: ^0.6.0
  html: ^0.13.3+3
  http: ^0.12.0
  html_unescape: ^1.0.2


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
